version: '3.8'
services:
  dev-db:
    image: postgres:13
    ports:
      - 5434:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: X4fDh*z5VexTg46wRj6Y
      POSTGRES_DB: nest
    networks:
      - vadimiro
networks:
  vadimiro:
